package com.github.kr328.zloader.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

abstract class CustomizeTask : DefaultTask() {
    @get:InputDirectory
    abstract val customizeFiles: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun doAction() {
        val files = (customizeFiles.get().asFile.listFiles()?.toList() ?: emptyList())
            .sortedBy { it.name }

        val customizeText = buildString {
            appendLine("# DO NOT EDIT")
            appendLine("# Generated by ZygoteLoader")
            appendLine()
            files.forEach {
                appendLine(". \"\$MODPATH/customize.d/${it.name}\" || abort \"! Load ${it.name} failed\"")
            }
            appendLine()
            appendLine("rm -rf \"\$MODPATH/customize.d\"")
        }

        outputDir.asFile.get().apply {
            mkdirs()

            resolve("customize.sh").writeText(customizeText)
        }
    }
}