package com.github.kr328.zloader.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

abstract class CustomizeTask : DefaultTask() {
    @get:InputDirectory
    abstract val customizeFiles: DirectoryProperty

    @get:InputDirectory
    abstract val checksumFiles: DirectoryProperty

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun doAction() {
        val customizes = customizeFiles.get().asFile.listFiles()?.toList() ?: emptyList()
        val checksums = checksumFiles.get().asFile.listFiles()?.toList() ?: emptyList()

        val files = (customizes + checksums).sortedBy { it.name }

        val customizeText = buildString {
            appendLine("# Generated by ZygoteLoader. DO NOT EDIT")
            appendLine()
            files.forEach {
                appendLine("[ -f \"\$MODPATH/customize.d/${it.name}\" ] || abort \"! Part '${it.name}' not found\"")
                appendLine(". \"\$MODPATH/customize.d/${it.name}\"")
            }
            appendLine()
            appendLine("rm -rf \"\$MODPATH/customize.d\"")
        }

        outputDir.asFile.get().apply {
            mkdirs()

            resolve("customize.sh").writeText(customizeText)
        }
    }
}