package com.github.kr328.gradle.zygote.tasks

import com.github.kr328.gradle.zygote.util.digestHexString
import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.security.MessageDigest

abstract class ChecksumTask : DefaultTask() {
    @get:InputDirectory
    abstract val inputDir: DirectoryProperty

    @get:OutputDirectory
    abstract val destinationDir: DirectoryProperty

    @TaskAction
    fun doAction() {
        val root = inputDir.get().asFile
        val sha256 = MessageDigest.getInstance("SHA-256")

        val script = root.walk()
            .filter { it.isFile }
            .map { it.relativeTo(root).invariantSeparatorsPath }
            .filterNot { it.startsWith("META-INF") }
            .sorted()
            .map {
                it to sha256.digestHexString(root.resolve(it).readBytes())
            }
            .joinToString("\n") {
                "do_verify ${it.first} ${it.second}"
            }

        destinationDir.get().asFile.resolve("customize.d").apply {
            mkdirs()

            resolve("00-verify-resources.sh").writeText(buildString {
                appendLine(
                    """
                    # Generated by ZygoteLoader. DO NOT EDIT.
                    
                    ui_print "- Verify module resources"
                    
                    function do_verify() {
                        [ -f "${'$'}MODPATH/$1" ] || abort "! Module resource '${'$'}1' not found"
                        
                        (echo "$2  ${'$'}MODPATH/$1" | sha256sum -c -s -) || abort "! Module resource '$1' verify failed"
                        
                        ui_print "  '$1' verified"
                    }
                    """.trimIndent()
                )
                appendLine()
                appendLine(script)
                appendLine()
                appendLine(
                    """
                    unset -f do_verify
                    """.trimIndent()
                )
            })
        }
    }
}