package com.github.kr328.gradle.zygote.tasks;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.InputDirectory;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.TaskAction;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.stream.Stream;

public abstract class CustomizeTask extends DefaultTask {
    private static final String CUSTOMIZE_HEADER = String.join("\n",
            "# Generated by ZygoteLoader. DO NOT EDIT."
    );
    private static final String CUSTOMIZE_TAIL = String.join("\n",
            "rm -rf $MODPATH/customize.d"
    );

    @InputDirectory
    public abstract DirectoryProperty getMergedDirectory();

    @Input
    public abstract Property<String> getChecksumFileName();

    @OutputFile
    public abstract RegularFileProperty getDestinationFile();

    @TaskAction
    public void doAction() throws Exception {
        final StringBuilder sb = new StringBuilder();

        sb.append(CUSTOMIZE_HEADER).append("\n\n");

        final Stream<String> customizes = Stream.concat(
                Stream.of(getChecksumFileName().get()),
                Files.list(getMergedDirectory().getAsFile().get().toPath().resolve("customize.d"))
                        .map(Path::getFileName)
                        .map(Path::toString)
        ).sorted();

        customizes.forEach(f -> {
            sb.append(String.format("[ -f \"$MODPATH/customize.d/%1$s\" ] || abort \"! Part '%1$s' not found\"", f)).append('\n');
            sb.append(String.format(". \"$MODPATH/customize.d/%1$s\"", f)).append('\n');
        });

        sb.append("\n\n").append(CUSTOMIZE_TAIL);

        Files.writeString(getDestinationFile().getAsFile().get().toPath(), sb);
    }
}
